### ISSUE TITLE
Configuration Proposal

### ISSUE THREAD

**Issue by tlhunter** [gschoberth/discord_bot_apex#2]
It looks like _config.json_ exports an object with three properties: `trackerToken`, `prefix`, and `token`.

I propose you create a _config.js_ file in the root instead. Inside that file, have it do something like this:

```javascript
const config = {
  trackerToken: process.env.TRACKER_TOKEN,
  prefix: process.env.COMMAND_PREFIX || '!!',
  token: process.env.DISCORD_TOKEN,
};

if (!config.trackerToken || !config.token) {
  console.error("Usage: TRACKER_TOKEN=<token> DISCORD_TOKEN=<token> ./index.js");
  process.exit(1);
}

module.exports = config;
```

This lets users run the application without touching the filesystem (i.e. writing to _config.json_). It will also print an error message if the application is run unconfigured, explaining how to configure it. This pattern is used in a lot of Node.js services. I think this website explains the concept really well: https://12factor.net/config

**Comment by gschoberth** [comment]
Implemented the suggested changes.
