### ISSUE TITLE
README Propsoal

### ISSUE THREAD

**Issue by tlhunter** [gschoberth/discord_bot_apex#3]
I propose adding a screenshot to the README file. One way to do it is to literally commit a _screenshot.png_ image to the repo, and then load that image in the README with something like this:

```markdown
![Screenshot of Discord Bot](./screenshot.png)
```

The screenshot should be of a recent image taken, with impressive number from your account, how it contextually looks within Discord (not just the generated image). I think this will really hit home with someone visiting the repository. They'll see the image and immediately know what the project does.

![20200217205811](https://user-images.githubusercontent.com/551402/74705392-8f6fcf80-51c8-11ea-9dec-2d21557a7175.png)

The README should also list the commands, their arguments, include links to the page for getting API tokens for A) Discord and B) the third party stats API.

Also, include the caveats with the third party API. Unfortunately, a lot of people that run the project will complain about the missing stats. By having having a warning that the upstream API is flaky and doesn't include all stats, you should be able to avoid some of those complaints.

**Comment by gschoberth** [comment]
Added in the changes to the README
